### ISSUE TITLE
Pi issue in gufunc lowering

### ISSUE THREAD

**Issue by ehsantn** [IntelLabs/numba#41]
The Pi example works with sequential lowering, but produces wrong output with gufunc lowering (stencil branch). Seems like there is a bug with the recent backend changes.

**Comment by ehsantn** [comment]
ping @ninegua @DrTodd13 .

**Comment by ninegua** [comment]
It's related to commit b1e646c. Another failing test was `test_randoms`, I traced it to this commit.
