### ISSUE TITLE
problem with copy propagation

### ISSUE THREAD

**Issue by ninegua** [IntelLabs/numba#5]
The following is a simplified description of the problem. If we had Numba IR that contains:

```
x = $1
...
x = inplace_binop(... , lhs = x)
...
z = x
```
Current copy propagation will think `x` can be replaced by `$1` for statement `z = x`, and rerwrite it as `z = $1`, which is wrong. Without copy propagation, it works.

I also noticed a workaround, i.e., if the incoming IR is:

```
x = $1
...
$2 = inplace_binop(..., lhs = x)
x = $2
...
z = x
```

Then copy propagation will not attempt to rewrite `z = x` with `z = $1`.  This workaround has been implemented in 27b3294d6804581dbb2a05364503df9ced98243f to avoid ssiue.

So the question is with how we treat variable assignments. I'm under the impression that the intermediate variable names introduced in Numba IR are all assigned once. So in both cases above, `x` does not start with `$` and shouldn't be considered as assigned once. I'm also curious why the second case works fine with copy propagation.

PS: to exactly reproduce the problem, run the following program with commit 27b3294d6804581dbb2a05364503df9ced98243f, and manually set `auto_parallel=True` in `compiler.py`. It'll print the sum to be 0, which is wrong.

```
import numpy as np
from numba import *

@njit(parallel=True)
def f(a):
    return np.sum(a)

a=np.arange(9)
print(a)
print(f(a))
```

**Comment by ehsantn** [comment]
This example works with sequential lowering but not gufunc. Could there be an issue with size variables?

**Comment by ehsantn** [comment]
commit https://github.com/IntelLabs/numba/commit/f8978a37a3449586ad143019b1f0bb4da220dd25 fixes the issue.

The problem was that copy propagation wasn't killing the copies to `x` when seeing the inplace operation. This didn't cause any problem anywhere else since Numba doesn't generate code like this (always assigns to temporaries). So, maybe your workaround is actually the right way to generate this code.

**Comment by ninegua** [comment]
Thanks for the fix!
