### ISSUE TITLE
array_size_var is wrongly removed

### ISSUE THREAD

**Issue by ninegua** [IntelLabs/numba#6]
It looks like some array size variable in `array_analysis.array_size_vars` are being removed before parfor lowering. To reproduce this, checkout c64e501ecf22f95209b64f6ea05d1b069a387c7d, manually set `auto_parallel` to `True` in `compiler.py`, and run `NUMBA_DEBUG_ARRAY_OPT=1 python3 runtests.py -f numba.tests.test_linalg.TestProduct`. Below are some related debug outputs:

```
...
array_size_vars:  {'a': [Var(asize0.1460, /opt/numba/numba/numba/tests/test_linalg.py (33)), Var(asize1.1463, /opt/numba/numba/numba/tests/test_linalg.py (33))], '$0.8': [Var(asize0.1460, /opt/numba/numba/numba/tests/test_linalg.py (33))], 'out': [Var(outsize0.1469, /opt/numba/numba/numba/tests/test_linalg.py (33))], '$0.7': [Var(asize0.1460, /opt/numba/numba/numba/tests/test_linalg.py (33))], 'b': [Var(bsize0.1466, /opt/numba/numba/numba/tests/test_linalg.py (33))]}
...
array_size_vars =  [('$0.7', [Var(asize0.1460, /opt/numba/numba/numba/tests/test_linalg.py (33))]), ('$0.8', [Var(asize0.1460, /opt/numba/numba/numba/tests/test_linalg.py (33))]), ('a', [Var(asize0.1460, /opt/numba/numba/numba/tests/test_linalg.py (33)), Var(asize1.1463, /opt/numba/numba/numba/tests/test_linalg.py (33))]), ('b', [Var(asize1.1463, /opt/numba/numba/numba/tests/test_linalg.py (33))]), ('out', [None])]
...
```

The size var for `out` becomes `[None]`, which eventually caused lowering to gufunc to fail. I don't quite understand how this got changed. Note that there are multiple other array_analysis passes in between, but I don't think those would affect this part. So I suspect it is related to `remove_dead_class_sizes`? 

In any case, I've made a workaround in 9bbbec0c8f085ed9a9ea926fd4bb4c3c837b248b to directly fetch array shapes in LLVM code so as to get past LinAlg tests. The above problem nevertheless is still there.

**Comment by ninegua** [comment]
Was this fixed already? @ehsantn

**Comment by ehsantn** [comment]
I think so.
